version: '3'

services:
  db:
    image: mariadb
    container_name: db
    ports:
    - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root-pass"
      - "MYSQL_DATABASE=Dev"
      - "MYSQL_USER=dev"
      - "MYSQL_PASSWORD=VerryGoodPasswordToUseInTestEnvironnement"

volumes:
  mysql:
