version: '3'

services:
  db:
    image: mariadb
    container_name: db
    ports:
    - "3306:3306"
    volumes:
      - mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=root-pass"
      - "MYSQL_DATABASE=test"
      - "MYSQL_USER=test"
      - "MYSQL_PASSWORD=test-pass"

volumes:
  mysql:
